###########
# site.title

title:    'BubbleTea'
subtitle: 'Minecraft Parkour using ObservationGrid and VideoProducers'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
